// Foundation resources (Phase A). These power security, audit, templates,
// notifications and saved views used by every other module.

export const ROLES = ['Admin', 'Quality', 'Production', 'Operator', 'Viewer'];

export const foundationResources = [
  {
    key: 'users',
    singular: 'User',
    plural: 'Users',
    group: 'Administration',
    icon: 'Users',
    isoClause: 'ISO 13485 §6.2 / ISO 9001 §7.2',
    titleField: 'full_name',
    // Only Admin manages users.
    permissions: { read: ['Admin'], write: ['Admin'] },
    fields: [
      { name: 'username', label: 'Username', type: 'text', required: true, width: 140 },
      { name: 'full_name', label: 'Full Name', type: 'text', required: true, width: 180 },
      { name: 'email', label: 'Email', type: 'text', width: 200 },
      { name: 'role', label: 'Role', type: 'select', options: ROLES, required: true, width: 120 },
      { name: 'department', label: 'Department', type: 'text', width: 150 },
      { name: 'active', label: 'Active', type: 'boolean', default: true, width: 90 },
      // password_hash is managed by the auth layer, never returned to the client.
      { name: 'password', label: 'Password', type: 'password', writeOnly: true, hideInTable: true },
    ],
  },
  {
    key: 'audit_log',
    singular: 'Audit Entry',
    plural: 'Audit Trail',
    group: 'Administration',
    icon: 'History',
    isoClause: 'ISO 13485 §4.2.5 (Records) / 21 CFR Part 11',
    titleField: 'summary',
    readOnly: true,
    permissions: { read: ['Admin', 'Quality'], write: [] },
    fields: [
      { name: 'ts', label: 'Timestamp', type: 'datetime', width: 170 },
      { name: 'actor', label: 'User', type: 'text', width: 140 },
      { name: 'action', label: 'Action', type: 'text', width: 100 },
      { name: 'resource', label: 'Resource', type: 'text', width: 140 },
      { name: 'record_id', label: 'Record', type: 'text', width: 130 },
      { name: 'summary', label: 'Summary', type: 'textarea', wrap: true, width: 320 },
      { name: 'signature', label: 'E-Signature', type: 'text', width: 160 },
    ],
  },
  {
    key: 'templates',
    singular: 'Template',
    plural: 'Templates',
    group: 'Administration',
    icon: 'FileText',
    isoClause: 'ISO 13485 §4.2.4 (Control of Documents)',
    titleField: 'name',
    permissions: { read: ROLES, write: ['Admin', 'Quality'] },
    fields: [
      { name: 'name', label: 'Template Name', type: 'text', required: true, width: 200 },
      { name: 'category', label: 'Category', type: 'select', width: 150,
        options: ['Form', 'Report', 'Label', 'Certificate', 'Protocol', 'Checklist'] },
      { name: 'module', label: 'Applies To Module', type: 'text', width: 160 },
      { name: 'version', label: 'Version', type: 'text', default: '1.0', width: 90 },
      { name: 'status', label: 'Status', type: 'select', default: 'Placeholder', width: 130,
        options: ['Placeholder', 'Draft', 'Released', 'Obsolete'] },
      { name: 'body', label: 'Template Body / Placeholder', type: 'textarea', wrap: true, width: 380,
        default: '— Placeholder. Upload or paste your controlled template here. —' },
      { name: 'notes', label: 'Notes', type: 'textarea', wrap: true, width: 260 },
    ],
  },
  {
    key: 'notifications',
    singular: 'Notification',
    plural: 'Notifications & Tasks',
    group: 'Administration',
    icon: 'Bell',
    isoClause: '—',
    titleField: 'title',
    permissions: { read: ROLES, write: ROLES },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, width: 220 },
      { name: 'kind', label: 'Type', type: 'select', default: 'Task', width: 110,
        options: ['Task', 'Alert', 'Approval', 'Reminder'] },
      { name: 'assignee', label: 'Assignee', type: 'text', width: 140 },
      { name: 'due_date', label: 'Due', type: 'date', width: 120 },
      { name: 'priority', label: 'Priority', type: 'select', default: 'Medium', width: 100,
        options: ['Low', 'Medium', 'High', 'Critical'] },
      { name: 'status', label: 'Status', type: 'select', default: 'Open', width: 110,
        options: ['Open', 'In Progress', 'Done', 'Cancelled'] },
      { name: 'link', label: 'Related Record', type: 'text', width: 160 },
    ],
  },
];
