// Production Core resources (Phase B).
import { ROLES } from './foundation.js';

const RW = { read: ROLES, write: ['Admin', 'Production', 'Quality'] };

export const productionResources = [
  {
    key: 'products',
    singular: 'Product Model',
    plural: 'Product Models',
    group: 'Production',
    icon: 'Cpu',
    isoClause: 'ISO 13485 §7.3 (Design & Development)',
    titleField: 'name',
    permissions: RW,
    fields: [
      { name: 'code', label: 'Model Code', type: 'text', required: true, width: 120 },
      { name: 'name', label: 'Model Name', type: 'text', required: true, width: 200 },
      { name: 'class', label: 'Device Class', type: 'select', options: ['Class I', 'Class IIa', 'Class IIb', 'Class III'], default: 'Class IIb', width: 110 },
      { name: 'type', label: 'Ventilator Type', type: 'select', width: 160,
        options: ['Invasive ICU', 'Non-Invasive (NIV)', 'Transport', 'Neonatal', 'High-Flow'] },
      { name: 'status', label: 'Lifecycle', type: 'select', default: 'Active', width: 120,
        options: ['Design', 'Active', 'On Hold', 'End of Life'] },
      { name: 'intended_use', label: 'Intended Use', type: 'textarea', wrap: true, width: 320 },
    ],
  },
  {
    key: 'bom',
    singular: 'BOM Line',
    plural: 'Bill of Materials',
    group: 'Production',
    icon: 'ListTree',
    isoClause: 'ISO 13485 §7.3.3 (Design Outputs)',
    titleField: 'component',
    permissions: RW,
    fields: [
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'level', label: 'Level', type: 'number', default: 1, width: 70 },
      { name: 'component', label: 'Component', type: 'text', required: true, width: 200 },
      { name: 'part_number', label: 'Part No.', type: 'text', width: 130 },
      { name: 'material_id', label: 'Linked Material', type: 'ref', ref: 'materials', width: 160 },
      { name: 'qty', label: 'Qty', type: 'number', default: 1, width: 70 },
      { name: 'uom', label: 'UoM', type: 'select', options: ['ea', 'm', 'kg', 'L', 'set'], default: 'ea', width: 70 },
      { name: 'revision', label: 'Rev', type: 'text', default: 'A', width: 70 },
      { name: 'critical', label: 'Critical (CTQ)', type: 'boolean', default: false, width: 110 },
    ],
  },
  {
    key: 'dmr',
    singular: 'Device Master Record',
    plural: 'Device Master Records (DMR)',
    group: 'Production',
    icon: 'BookLock',
    isoClause: 'ISO 13485 §4.2.3 (Medical Device File)',
    titleField: 'title',
    permissions: { read: ROLES, write: ['Admin', 'Quality'] },
    fields: [
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'title', label: 'DMR Title', type: 'text', required: true, width: 220 },
      { name: 'revision', label: 'Revision', type: 'text', default: 'A', width: 80 },
      { name: 'status', label: 'Status', type: 'select', default: 'Draft', width: 120,
        options: ['Draft', 'Under Review', 'Approved', 'Obsolete'] },
      { name: 'specifications', label: 'Device Specifications', type: 'textarea', wrap: true, width: 320 },
      { name: 'process_refs', label: 'Process / Routing Refs', type: 'textarea', wrap: true, width: 260 },
      { name: 'approved_by', label: 'Approved By', type: 'text', width: 140 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
    ],
  },
  {
    key: 'work_orders',
    singular: 'Work Order',
    plural: 'Work Orders',
    group: 'Production',
    icon: 'ClipboardList',
    isoClause: 'ISO 13485 §7.5.1 (Control of Production)',
    titleField: 'wo_number',
    permissions: RW,
    fields: [
      { name: 'wo_number', label: 'WO #', type: 'text', required: true, width: 120 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'qty', label: 'Qty', type: 'number', default: 1, width: 70 },
      { name: 'priority', label: 'Priority', type: 'select', default: 'Normal', options: ['Low', 'Normal', 'High', 'Rush'], width: 100 },
      { name: 'status', label: 'Status', type: 'select', default: 'Planned', width: 130,
        options: ['Planned', 'Released', 'In Progress', 'On Hold', 'Completed', 'Cancelled'] },
      { name: 'planned_start', label: 'Planned Start', type: 'date', width: 130 },
      { name: 'planned_end', label: 'Planned End', type: 'date', width: 130 },
      { name: 'line', label: 'Production Line', type: 'select', options: ['Line 1', 'Line 2', 'Line 3', 'Clean Room A'], width: 130 },
      { name: 'notes', label: 'Notes', type: 'textarea', wrap: true, width: 260 },
    ],
  },
  {
    key: 'routings',
    singular: 'Routing Step',
    plural: 'Routing & Work Instructions',
    group: 'Production',
    icon: 'Route',
    isoClause: 'ISO 13485 §7.5.1 / §4.2.4',
    titleField: 'operation',
    permissions: RW,
    fields: [
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'seq', label: 'Seq', type: 'number', default: 10, width: 70 },
      { name: 'operation', label: 'Operation', type: 'text', required: true, width: 200 },
      { name: 'station', label: 'Station', type: 'text', width: 140 },
      { name: 'std_time_min', label: 'Std Time (min)', type: 'number', width: 120 },
      { name: 'instructions', label: 'Work Instructions', type: 'textarea', wrap: true, width: 360 },
      { name: 'inspection_required', label: 'Inspection Pt', type: 'boolean', default: false, width: 110 },
    ],
  },
  {
    key: 'shopfloor',
    singular: 'Shop Floor Log',
    plural: 'Shop Floor Control',
    group: 'Production',
    icon: 'Factory',
    isoClause: 'ISO 13485 §7.5.1',
    titleField: 'wo_number',
    permissions: { read: ROLES, write: ['Admin', 'Production', 'Operator', 'Quality'] },
    fields: [
      { name: 'wo_number', label: 'WO #', type: 'ref', ref: 'work_orders', refField: 'wo_number', required: true, width: 120 },
      { name: 'station', label: 'Station', type: 'text', width: 140 },
      { name: 'operator', label: 'Operator', type: 'text', width: 140 },
      { name: 'operation', label: 'Operation', type: 'text', width: 180 },
      { name: 'status', label: 'Status', type: 'select', default: 'Started', options: ['Started', 'Paused', 'Completed', 'Reject'], width: 110 },
      { name: 'start_ts', label: 'Start', type: 'datetime', width: 160 },
      { name: 'end_ts', label: 'End', type: 'datetime', width: 160 },
      { name: 'qty_good', label: 'Qty Good', type: 'number', default: 0, width: 90 },
      { name: 'qty_scrap', label: 'Qty Scrap', type: 'number', default: 0, width: 90 },
    ],
  },
  {
    key: 'devices',
    singular: 'Device History Record',
    plural: 'Device History Records (DHR)',
    group: 'Production',
    icon: 'ScanLine',
    isoClause: 'ISO 13485 §7.5.1 / §8.3 (Traceability)',
    titleField: 'serial_number',
    permissions: { read: ROLES, write: ['Admin', 'Production', 'Quality'] },
    fields: [
      { name: 'serial_number', label: 'Serial Number', type: 'text', required: true, width: 150 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'wo_number', label: 'Work Order', type: 'ref', ref: 'work_orders', refField: 'wo_number', width: 120 },
      { name: 'lot_number', label: 'Lot/Batch', type: 'text', width: 120 },
      { name: 'build_status', label: 'Build Status', type: 'select', default: 'In Build', width: 130,
        options: ['In Build', 'Built', 'In Test', 'Released', 'Quarantined', 'Shipped'] },
      { name: 'udi', label: 'UDI', type: 'ref', ref: 'udi', refField: 'udi_di', width: 170 },
      { name: 'built_on', label: 'Built On', type: 'date', width: 120 },
      { name: 'released_on', label: 'Released On', type: 'date', width: 120 },
      { name: 'release_signature', label: 'Release E-Signature', type: 'signature', width: 170 },
      { name: 'genealogy', label: 'Material Genealogy', type: 'textarea', wrap: true, width: 320 },
    ],
  },
  {
    key: 'udi',
    singular: 'UDI Record',
    plural: 'UDI Registry',
    group: 'Production',
    icon: 'QrCode',
    isoClause: 'ISO 13485 §7.5.1 / EU MDR UDI',
    titleField: 'udi_di',
    permissions: { read: ROLES, write: ['Admin', 'Quality'] },
    fields: [
      { name: 'udi_di', label: 'UDI-DI', type: 'text', required: true, width: 180 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', required: true, width: 180 },
      { name: 'issuing_agency', label: 'Issuing Agency', type: 'select', options: ['GS1', 'HIBCC', 'ICCBBA'], default: 'GS1', width: 130 },
      { name: 'gmdn', label: 'GMDN Code', type: 'text', width: 110 },
      { name: 'package_level', label: 'Package Level', type: 'select', options: ['Unit', 'Box', 'Case'], default: 'Unit', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Active', options: ['Active', 'Obsolete'], width: 100 },
    ],
  },
  {
    key: 'schedule',
    singular: 'Schedule Entry',
    plural: 'Production Schedule',
    group: 'Production',
    icon: 'CalendarRange',
    isoClause: 'ISO 9001 §8.1 (Operational Planning)',
    titleField: 'title',
    permissions: RW,
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, width: 200 },
      { name: 'wo_number', label: 'Work Order', type: 'ref', ref: 'work_orders', refField: 'wo_number', width: 120 },
      { name: 'resource', label: 'Resource/Line', type: 'select', options: ['Line 1', 'Line 2', 'Line 3', 'Clean Room A', 'Test Bench'], width: 130 },
      { name: 'start', label: 'Start', type: 'date', required: true, width: 120 },
      { name: 'end', label: 'End', type: 'date', required: true, width: 120 },
      { name: 'capacity_pct', label: 'Capacity %', type: 'number', default: 100, width: 100 },
    ],
  },
];
