// Quality & Compliance resources (Phase C) — ISO 13485 / ISO 9001 / ISO 14971.
import { ROLES } from './foundation.js';

const QW = { read: ROLES, write: ['Admin', 'Quality'] };
const QP = { read: ROLES, write: ['Admin', 'Quality', 'Production'] };

const DISPOSITIONS = ['Use As Is', 'Rework', 'Repair', 'Scrap', 'Return to Supplier', 'Pending'];
const STATUS_INV = ['Open', 'Investigation', 'Action', 'Verification', 'Closed'];

export const qualityResources = [
  {
    key: 'documents',
    singular: 'Controlled Document',
    plural: 'Document Control',
    group: 'Quality',
    icon: 'FileCheck2',
    isoClause: 'ISO 13485 §4.2.4 / ISO 9001 §7.5',
    titleField: 'title',
    permissions: QW,
    fields: [
      { name: 'doc_number', label: 'Doc #', type: 'text', required: true, width: 120 },
      { name: 'title', label: 'Title', type: 'text', required: true, width: 240 },
      { name: 'type', label: 'Type', type: 'select', width: 130,
        options: ['SOP', 'Work Instruction', 'Form', 'Policy', 'Quality Manual', 'Specification'] },
      { name: 'revision', label: 'Rev', type: 'text', default: 'A', width: 70 },
      { name: 'status', label: 'Status', type: 'select', default: 'Draft', width: 120,
        options: ['Draft', 'In Review', 'Approved', 'Released', 'Obsolete'] },
      { name: 'owner', label: 'Owner', type: 'text', width: 130 },
      { name: 'effective_date', label: 'Effective', type: 'date', width: 120 },
      { name: 'review_date', label: 'Next Review', type: 'date', width: 120 },
      { name: 'signature', label: 'Approval E-Signature', type: 'signature', width: 170 },
    ],
  },
  {
    key: 'inspections',
    singular: 'Inspection',
    plural: 'Inspections (Incoming/In-Process/Final)',
    group: 'Quality',
    icon: 'SearchCheck',
    isoClause: 'ISO 13485 §7.4.3 / §8.2.6 (Monitoring of Product)',
    titleField: 'ref',
    permissions: QP,
    fields: [
      { name: 'ref', label: 'Inspection Ref', type: 'text', required: true, width: 130 },
      { name: 'stage', label: 'Stage', type: 'select', required: true, width: 130,
        options: ['Incoming', 'In-Process', 'Final', 'Device Release'] },
      { name: 'subject', label: 'Subject (Lot/Serial/WO)', type: 'text', width: 180 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'inspector', label: 'Inspector', type: 'text', width: 130 },
      { name: 'sample_size', label: 'Sample', type: 'number', width: 80 },
      { name: 'defects', label: 'Defects', type: 'number', default: 0, width: 80 },
      { name: 'result', label: 'Result', type: 'select', default: 'Pending', options: ['Pending', 'Pass', 'Fail', 'Conditional'], width: 110 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
      { name: 'notes', label: 'Findings', type: 'textarea', wrap: true, width: 300 },
    ],
  },
  {
    key: 'ncr',
    singular: 'Nonconformance',
    plural: 'Nonconforming Product (NCR)',
    group: 'Quality',
    icon: 'AlertTriangle',
    isoClause: 'ISO 13485 §8.3 / ISO 9001 §8.7',
    titleField: 'ncr_number',
    permissions: QP,
    fields: [
      { name: 'ncr_number', label: 'NCR #', type: 'text', required: true, width: 120 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'source', label: 'Source', type: 'select', width: 140,
        options: ['Incoming', 'In-Process', 'Final', 'Customer', 'Audit', 'Field'] },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'subject', label: 'Affected (Lot/Serial)', type: 'text', width: 160 },
      { name: 'qty', label: 'Qty', type: 'number', default: 1, width: 70 },
      { name: 'severity', label: 'Severity', type: 'select', default: 'Minor', options: ['Minor', 'Major', 'Critical'], width: 100 },
      { name: 'description', label: 'Description', type: 'textarea', wrap: true, width: 320, required: true },
      { name: 'disposition', label: 'Disposition', type: 'select', options: DISPOSITIONS, default: 'Pending', width: 140 },
      { name: 'capa_id', label: 'Linked CAPA', type: 'ref', ref: 'capa', refField: 'capa_number', width: 130 },
      { name: 'status', label: 'Status', type: 'select', default: 'Open', options: ['Open', 'Dispositioned', 'Closed'], width: 120 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
    ],
  },
  {
    key: 'capa',
    singular: 'CAPA',
    plural: 'CAPA',
    group: 'Quality',
    icon: 'Wrench',
    isoClause: 'ISO 13485 §8.5.2/§8.5.3 / ISO 9001 §10.2',
    titleField: 'capa_number',
    permissions: QW,
    fields: [
      { name: 'capa_number', label: 'CAPA #', type: 'text', required: true, width: 120 },
      { name: 'type', label: 'Type', type: 'select', default: 'Corrective', options: ['Corrective', 'Preventive'], width: 120 },
      { name: 'source', label: 'Source', type: 'select', width: 130,
        options: ['NCR', 'Complaint', 'Audit', 'Management Review', 'Trend', 'Adverse Event'] },
      { name: 'title', label: 'Title', type: 'text', required: true, width: 240 },
      { name: 'problem_statement', label: 'Problem Statement', type: 'textarea', wrap: true, width: 320 },
      { name: 'root_cause', label: 'Root Cause', type: 'textarea', wrap: true, width: 300 },
      { name: 'action_plan', label: 'Action Plan', type: 'textarea', wrap: true, width: 300 },
      { name: 'owner', label: 'Owner', type: 'text', width: 130 },
      { name: 'due_date', label: 'Due', type: 'date', width: 120 },
      { name: 'effectiveness', label: 'Effectiveness Check', type: 'textarea', wrap: true, width: 260 },
      { name: 'status', label: 'Status', type: 'select', default: 'Open', options: STATUS_INV, width: 120 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
    ],
  },
  {
    key: 'complaints',
    singular: 'Complaint',
    plural: 'Customer Complaints',
    group: 'Quality',
    icon: 'MessageSquareWarning',
    isoClause: 'ISO 13485 §8.2.2 (Complaint Handling)',
    titleField: 'complaint_number',
    permissions: QW,
    fields: [
      { name: 'complaint_number', label: 'Complaint #', type: 'text', required: true, width: 130 },
      { name: 'date_received', label: 'Received', type: 'date', width: 120 },
      { name: 'customer', label: 'Customer', type: 'text', width: 180 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'serial_number', label: 'Serial', type: 'ref', ref: 'devices', refField: 'serial_number', width: 140 },
      { name: 'description', label: 'Complaint Detail', type: 'textarea', wrap: true, width: 320, required: true },
      { name: 'reportable', label: 'Reportable (MDR)?', type: 'boolean', default: false, width: 130 },
      { name: 'investigation', label: 'Investigation', type: 'textarea', wrap: true, width: 300 },
      { name: 'capa_id', label: 'Linked CAPA', type: 'ref', ref: 'capa', refField: 'capa_number', width: 130 },
      { name: 'status', label: 'Status', type: 'select', default: 'Open', options: STATUS_INV, width: 120 },
    ],
  },
  {
    key: 'adverse_events',
    singular: 'Adverse Event',
    plural: 'Adverse Events / Vigilance (MDR)',
    group: 'Quality',
    icon: 'Siren',
    isoClause: 'ISO 13485 §8.2.3 / EU MDR Vigilance / FDA MDR',
    titleField: 'event_number',
    permissions: QW,
    fields: [
      { name: 'event_number', label: 'Event #', type: 'text', required: true, width: 120 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'serial_number', label: 'Serial', type: 'ref', ref: 'devices', refField: 'serial_number', width: 140 },
      { name: 'event_type', label: 'Event Type', type: 'select', width: 150,
        options: ['Malfunction', 'Injury', 'Death', 'Near Miss'] },
      { name: 'description', label: 'Description', type: 'textarea', wrap: true, width: 320, required: true },
      { name: 'authority', label: 'Reported To', type: 'select', options: ['FDA', 'EU Competent Authority', 'MHRA', 'CDSCO', 'Not Reportable'], width: 170 },
      { name: 'report_due', label: 'Report Due', type: 'date', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Open', options: ['Open', 'Reported', 'Closed'], width: 110 },
    ],
  },
  {
    key: 'risks',
    singular: 'Risk / FMEA',
    plural: 'Risk Management (ISO 14971)',
    group: 'Quality',
    icon: 'ShieldAlert',
    isoClause: 'ISO 14971 / ISO 13485 §7.1',
    titleField: 'item',
    permissions: QW,
    fields: [
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'item', label: 'Hazard / Failure Mode', type: 'text', required: true, width: 220 },
      { name: 'cause', label: 'Cause', type: 'textarea', wrap: true, width: 240 },
      { name: 'effect', label: 'Effect / Harm', type: 'textarea', wrap: true, width: 240 },
      { name: 'severity', label: 'Sev (1-5)', type: 'number', default: 3, width: 90 },
      { name: 'occurrence', label: 'Occ (1-5)', type: 'number', default: 3, width: 90 },
      { name: 'detection', label: 'Det (1-5)', type: 'number', default: 3, width: 90 },
      { name: 'rpn', label: 'RPN', type: 'number', computed: 'severity*occurrence*detection', width: 80 },
      { name: 'mitigation', label: 'Risk Control', type: 'textarea', wrap: true, width: 280 },
      { name: 'residual', label: 'Residual Risk', type: 'select', options: ['Acceptable', 'ALARP', 'Unacceptable'], default: 'ALARP', width: 130 },
    ],
  },
  {
    key: 'validations',
    singular: 'Validation',
    plural: 'Process Validation (IQ/OQ/PQ)',
    group: 'Quality',
    icon: 'BadgeCheck',
    isoClause: 'ISO 13485 §7.5.6 (Validation of Processes)',
    titleField: 'protocol',
    permissions: QW,
    fields: [
      { name: 'protocol', label: 'Protocol #', type: 'text', required: true, width: 130 },
      { name: 'process', label: 'Process / Equipment', type: 'text', width: 200 },
      { name: 'phase', label: 'Phase', type: 'select', options: ['IQ', 'OQ', 'PQ', 'Re-Validation'], default: 'IQ', width: 110 },
      { name: 'acceptance', label: 'Acceptance Criteria', type: 'textarea', wrap: true, width: 300 },
      { name: 'result', label: 'Result', type: 'select', default: 'In Progress', options: ['In Progress', 'Pass', 'Fail'], width: 120 },
      { name: 'executed_by', label: 'Executed By', type: 'text', width: 140 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
    ],
  },
  {
    key: 'calibration',
    singular: 'Calibration Record',
    plural: 'Calibration Management',
    group: 'Quality',
    icon: 'Gauge',
    isoClause: 'ISO 13485 §7.6 (Monitoring & Measuring Equipment)',
    titleField: 'equipment',
    permissions: QP,
    fields: [
      { name: 'equipment', label: 'Equipment', type: 'text', required: true, width: 200 },
      { name: 'asset_id', label: 'Asset ID', type: 'text', width: 120 },
      { name: 'last_cal', label: 'Last Calibration', type: 'date', width: 140 },
      { name: 'next_cal', label: 'Next Due', type: 'date', width: 130 },
      { name: 'interval_days', label: 'Interval (days)', type: 'number', default: 365, width: 120 },
      { name: 'result', label: 'Result', type: 'select', default: 'Pass', options: ['Pass', 'Fail', 'Adjusted'], width: 100 },
      { name: 'performed_by', label: 'Performed By', type: 'text', width: 140 },
      { name: 'status', label: 'Status', type: 'select', default: 'In Service', options: ['In Service', 'Out of Service', 'Due', 'Overdue'], width: 130 },
    ],
  },
  {
    key: 'maintenance',
    singular: 'PM Record',
    plural: 'Preventive Maintenance',
    group: 'Quality',
    icon: 'Settings',
    isoClause: 'ISO 13485 §6.3 (Infrastructure)',
    titleField: 'equipment',
    permissions: QP,
    fields: [
      { name: 'equipment', label: 'Equipment', type: 'text', required: true, width: 200 },
      { name: 'asset_id', label: 'Asset ID', type: 'text', width: 120 },
      { name: 'task', label: 'Task', type: 'text', width: 220 },
      { name: 'frequency', label: 'Frequency', type: 'select', options: ['Weekly', 'Monthly', 'Quarterly', 'Annual'], default: 'Monthly', width: 120 },
      { name: 'last_done', label: 'Last Done', type: 'date', width: 120 },
      { name: 'next_due', label: 'Next Due', type: 'date', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Scheduled', options: ['Scheduled', 'Done', 'Overdue'], width: 110 },
      { name: 'technician', label: 'Technician', type: 'text', width: 140 },
    ],
  },
  {
    key: 'audits',
    singular: 'Internal Audit',
    plural: 'Internal Audits',
    group: 'Quality',
    icon: 'ClipboardCheck',
    isoClause: 'ISO 13485 §8.2.4 / ISO 9001 §9.2',
    titleField: 'audit_number',
    permissions: QW,
    fields: [
      { name: 'audit_number', label: 'Audit #', type: 'text', required: true, width: 110 },
      { name: 'scope', label: 'Scope / Area', type: 'text', width: 220 },
      { name: 'standard', label: 'Standard', type: 'select', options: ['ISO 13485', 'ISO 9001', 'Both', 'FDA QSR'], default: 'Both', width: 120 },
      { name: 'auditor', label: 'Lead Auditor', type: 'text', width: 140 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'findings', label: 'Findings', type: 'textarea', wrap: true, width: 320 },
      { name: 'nc_count', label: 'NCs', type: 'number', default: 0, width: 70 },
      { name: 'status', label: 'Status', type: 'select', default: 'Planned', options: ['Planned', 'In Progress', 'Reporting', 'Closed'], width: 120 },
    ],
  },
  {
    key: 'management_review',
    singular: 'Management Review',
    plural: 'Management Reviews',
    group: 'Quality',
    icon: 'Presentation',
    isoClause: 'ISO 13485 §5.6 / ISO 9001 §9.3',
    titleField: 'title',
    permissions: { read: ['Admin', 'Quality'], write: ['Admin', 'Quality'] },
    fields: [
      { name: 'title', label: 'Title', type: 'text', required: true, width: 220 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'attendees', label: 'Attendees', type: 'textarea', wrap: true, width: 240 },
      { name: 'inputs', label: 'Review Inputs', type: 'textarea', wrap: true, width: 300 },
      { name: 'outputs', label: 'Outputs / Decisions', type: 'textarea', wrap: true, width: 300 },
      { name: 'actions', label: 'Action Items', type: 'textarea', wrap: true, width: 280 },
      { name: 'signature', label: 'E-Signature', type: 'signature', width: 160 },
    ],
  },
  {
    key: 'training',
    singular: 'Training Record',
    plural: 'Training & Competence',
    group: 'Quality',
    icon: 'GraduationCap',
    isoClause: 'ISO 13485 §6.2 / ISO 9001 §7.2',
    titleField: 'employee',
    permissions: QW,
    fields: [
      { name: 'employee', label: 'Employee', type: 'text', required: true, width: 160 },
      { name: 'department', label: 'Department', type: 'text', width: 140 },
      { name: 'course', label: 'Course / Document', type: 'text', width: 220 },
      { name: 'doc_id', label: 'Linked Document', type: 'ref', ref: 'documents', refField: 'doc_number', width: 150 },
      { name: 'completed_on', label: 'Completed', type: 'date', width: 120 },
      { name: 'expires_on', label: 'Expires', type: 'date', width: 120 },
      { name: 'result', label: 'Result', type: 'select', options: ['Competent', 'In Training', 'Failed'], default: 'Competent', width: 120 },
      { name: 'trainer', label: 'Trainer', type: 'text', width: 140 },
    ],
  },
  {
    key: 'spc',
    singular: 'SPC Measurement',
    plural: 'SPC / Statistical Quality',
    group: 'Quality',
    icon: 'LineChart',
    isoClause: 'ISO 13485 §8.4 / ISO 9001 §9.1.3',
    titleField: 'characteristic',
    permissions: QP,
    fields: [
      { name: 'characteristic', label: 'Characteristic (CTQ)', type: 'text', required: true, width: 200 },
      { name: 'product_id', label: 'Product Model', type: 'ref', ref: 'products', width: 170 },
      { name: 'subgroup', label: 'Subgroup', type: 'number', default: 1, width: 90 },
      { name: 'value', label: 'Measured Value', type: 'number', required: true, width: 120 },
      { name: 'lsl', label: 'LSL', type: 'number', width: 80 },
      { name: 'usl', label: 'USL', type: 'number', width: 80 },
      { name: 'date', label: 'Date', type: 'date', width: 120 },
      { name: 'operator', label: 'Operator', type: 'text', width: 130 },
    ],
  },
];
