// Supply Chain & Inventory resources (Phase D).
import { ROLES } from './foundation.js';

const SW = { read: ROLES, write: ['Admin', 'Production', 'Quality'] };

export const supplyResources = [
  {
    key: 'suppliers',
    singular: 'Supplier',
    plural: 'Suppliers',
    group: 'Supply Chain',
    icon: 'Truck',
    isoClause: 'ISO 13485 §7.4.1 (Purchasing Process)',
    titleField: 'name',
    permissions: SW,
    fields: [
      { name: 'code', label: 'Supplier Code', type: 'text', required: true, width: 120 },
      { name: 'name', label: 'Name', type: 'text', required: true, width: 220 },
      { name: 'category', label: 'Category', type: 'select', width: 150,
        options: ['Critical', 'Major', 'Minor', 'Service'] },
      { name: 'approved', label: 'Approved (ASL)', type: 'boolean', default: false, width: 120 },
      { name: 'score', label: 'Scorecard (0-100)', type: 'number', default: 80, width: 130 },
      { name: 'last_audit', label: 'Last Audit', type: 'date', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Approved', options: ['Approved', 'Conditional', 'Probation', 'Disqualified'], width: 130 },
      { name: 'contact', label: 'Contact', type: 'text', width: 180 },
    ],
  },
  {
    key: 'materials',
    singular: 'Material',
    plural: 'Inventory / Materials',
    group: 'Supply Chain',
    icon: 'Package',
    isoClause: 'ISO 13485 §7.5.8 (Identification) / §7.4.3',
    titleField: 'name',
    permissions: SW,
    fields: [
      { name: 'part_number', label: 'Part No.', type: 'text', required: true, width: 130 },
      { name: 'name', label: 'Material', type: 'text', required: true, width: 220 },
      { name: 'category', label: 'Category', type: 'select', width: 150,
        options: ['Electronic', 'Mechanical', 'Pneumatic', 'Sensor', 'Sterile', 'Packaging', 'Consumable'] },
      { name: 'supplier_id', label: 'Supplier', type: 'ref', ref: 'suppliers', width: 170 },
      { name: 'lot_number', label: 'Lot/Batch', type: 'text', width: 120 },
      { name: 'qty_on_hand', label: 'On Hand', type: 'number', default: 0, width: 100 },
      { name: 'uom', label: 'UoM', type: 'select', options: ['ea', 'm', 'kg', 'L', 'set'], default: 'ea', width: 70 },
      { name: 'min_qty', label: 'Min', type: 'number', default: 0, width: 70 },
      { name: 'location', label: 'Location', type: 'text', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Available', options: ['Available', 'Quarantine', 'Rejected', 'Expired'], width: 120 },
      { name: 'expiry', label: 'Expiry', type: 'date', width: 120 },
    ],
  },
  {
    key: 'purchase_orders',
    singular: 'Purchase Order',
    plural: 'Purchase Orders',
    group: 'Supply Chain',
    icon: 'ShoppingCart',
    isoClause: 'ISO 13485 §7.4.2 (Purchasing Information)',
    titleField: 'po_number',
    permissions: SW,
    fields: [
      { name: 'po_number', label: 'PO #', type: 'text', required: true, width: 120 },
      { name: 'supplier_id', label: 'Supplier', type: 'ref', ref: 'suppliers', required: true, width: 180 },
      { name: 'material_id', label: 'Material', type: 'ref', ref: 'materials', width: 180 },
      { name: 'qty', label: 'Qty', type: 'number', default: 1, width: 80 },
      { name: 'unit_price', label: 'Unit Price', type: 'number', width: 100 },
      { name: 'order_date', label: 'Ordered', type: 'date', width: 120 },
      { name: 'due_date', label: 'Due', type: 'date', width: 120 },
      { name: 'status', label: 'Status', type: 'select', default: 'Draft', width: 120,
        options: ['Draft', 'Approved', 'Sent', 'Received', 'Closed', 'Cancelled'] },
    ],
  },
  {
    key: 'receiving',
    singular: 'Goods Receipt',
    plural: 'Goods Receiving',
    group: 'Supply Chain',
    icon: 'PackageCheck',
    isoClause: 'ISO 13485 §7.4.3 (Verification of Purchased Product)',
    titleField: 'grn_number',
    permissions: SW,
    fields: [
      { name: 'grn_number', label: 'GRN #', type: 'text', required: true, width: 120 },
      { name: 'po_number', label: 'PO #', type: 'ref', ref: 'purchase_orders', refField: 'po_number', width: 120 },
      { name: 'supplier_id', label: 'Supplier', type: 'ref', ref: 'suppliers', width: 170 },
      { name: 'material_id', label: 'Material', type: 'ref', ref: 'materials', width: 180 },
      { name: 'lot_number', label: 'Lot/Batch', type: 'text', width: 120 },
      { name: 'qty_received', label: 'Qty Recd', type: 'number', default: 0, width: 100 },
      { name: 'received_on', label: 'Received', type: 'date', width: 120 },
      { name: 'inspection_ref', label: 'Inspection Ref', type: 'ref', ref: 'inspections', refField: 'ref', width: 150 },
      { name: 'status', label: 'Status', type: 'select', default: 'Pending QC', options: ['Pending QC', 'Accepted', 'Rejected', 'Partial'], width: 130 },
    ],
  },
];
